### ISSUE TITLE
error: no member named 'code_fetch_hook' in 'struct mrb_state'

### ISSUE THREAD

**Issue by jarthod** [miura1729/mruby-profiler#1]
Hi!

I just tried compiling mruby 1.2 with your profiler and got the following error:

```
CC    build/mrbgems/mruby-profiler/src/profiler.c -> build/host/mrbgems/mruby-profiler/src/profiler.o
/home/bigbourin/work/words_path/mruby-1.2.0/build/mrbgems/mruby-profiler/src/profiler.c:627:8: error: no member named 'code_fetch_hook' in 'struct mrb_state'
  mrb->code_fetch_hook = prof_code_fetch_hook;
  ~~~  ^
```

Do you have any idea what could be the cause ?

**Comment by Asmod4n** [comment]
I believe you have to enable debugging, take a look where mrb_state is declared

**Comment by jarthod** [comment]
Ok It seems having `enable_debug` is not enough, I had to add `conf.cc.defines = %w(MRB_ENABLE_DEBUG_HOOK)` too. It's working now, thanks.
